version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: pd-mongo
    ports:
        - "27017:27017"
  redis:
    image: redis:alpine
    container_name: pd-redis
    ports:
      - "6379:6379"
  docker:
      image: neo4j:latest
      container_name: pd-neo4j
      ports:
        - "7474:7474"
        - "7687:7687"